/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TransparenciaRouteImport } from './routes/transparencia'
import { Route as SaqueRouteImport } from './routes/saque'
import { Route as RegistrarRouteImport } from './routes/registrar'
import { Route as EsgRouteImport } from './routes/esg'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ColetaRouteImport } from './routes/coleta'
import { Route as IndexRouteImport } from './routes/index'

const TransparenciaRoute = TransparenciaRouteImport.update({
  id: '/transparencia',
  path: '/transparencia',
  getParentRoute: () => rootRouteImport,
} as any)
const SaqueRoute = SaqueRouteImport.update({
  id: '/saque',
  path: '/saque',
  getParentRoute: () => rootRouteImport,
} as any)
const RegistrarRoute = RegistrarRouteImport.update({
  id: '/registrar',
  path: '/registrar',
  getParentRoute: () => rootRouteImport,
} as any)
const EsgRoute = EsgRouteImport.update({
  id: '/esg',
  path: '/esg',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ColetaRoute = ColetaRouteImport.update({
  id: '/coleta',
  path: '/coleta',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/coleta': typeof ColetaRoute
  '/dashboard': typeof DashboardRoute
  '/esg': typeof EsgRoute
  '/registrar': typeof RegistrarRoute
  '/saque': typeof SaqueRoute
  '/transparencia': typeof TransparenciaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/coleta': typeof ColetaRoute
  '/dashboard': typeof DashboardRoute
  '/esg': typeof EsgRoute
  '/registrar': typeof RegistrarRoute
  '/saque': typeof SaqueRoute
  '/transparencia': typeof TransparenciaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/coleta': typeof ColetaRoute
  '/dashboard': typeof DashboardRoute
  '/esg': typeof EsgRoute
  '/registrar': typeof RegistrarRoute
  '/saque': typeof SaqueRoute
  '/transparencia': typeof TransparenciaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/coleta'
    | '/dashboard'
    | '/esg'
    | '/registrar'
    | '/saque'
    | '/transparencia'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/coleta'
    | '/dashboard'
    | '/esg'
    | '/registrar'
    | '/saque'
    | '/transparencia'
  id:
    | '__root__'
    | '/'
    | '/coleta'
    | '/dashboard'
    | '/esg'
    | '/registrar'
    | '/saque'
    | '/transparencia'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ColetaRoute: typeof ColetaRoute
  DashboardRoute: typeof DashboardRoute
  EsgRoute: typeof EsgRoute
  RegistrarRoute: typeof RegistrarRoute
  SaqueRoute: typeof SaqueRoute
  TransparenciaRoute: typeof TransparenciaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/transparencia': {
      id: '/transparencia'
      path: '/transparencia'
      fullPath: '/transparencia'
      preLoaderRoute: typeof TransparenciaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/saque': {
      id: '/saque'
      path: '/saque'
      fullPath: '/saque'
      preLoaderRoute: typeof SaqueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/registrar': {
      id: '/registrar'
      path: '/registrar'
      fullPath: '/registrar'
      preLoaderRoute: typeof RegistrarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/esg': {
      id: '/esg'
      path: '/esg'
      fullPath: '/esg'
      preLoaderRoute: typeof EsgRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coleta': {
      id: '/coleta'
      path: '/coleta'
      fullPath: '/coleta'
      preLoaderRoute: typeof ColetaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ColetaRoute: ColetaRoute,
  DashboardRoute: DashboardRoute,
  EsgRoute: EsgRoute,
  RegistrarRoute: RegistrarRoute,
  SaqueRoute: SaqueRoute,
  TransparenciaRoute: TransparenciaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
